name: CI
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.vscode'
      - '*.md'
  push:
    branches:
      - main
jobs:
  ci_check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Moonup
        uses: chawyehsu/setup-moonup@v0.1.0

      - name: Run Tests
        run: moon test -v
